baseURL: https://www.kenton.wang/
languageCode: zh-cn
defaultContentLanguage: zh-cn
theme: coder
canonifyurls: true
uglyurls: true

params:
  since: 2022
  avatarURL: "images/avatar.jpg"
  keywords: "blog,developer,personal,elixir"
  customJS:
    - "js/busuanzi.pure.mini.js"
  social:
    - name: Email
      icon: "fa fa-brands fa-qq fa-2x"
      weight: 1
      url: "https://jq.qq.com/?_wv=1027&k=gzB4umnU"
    - name: Github
      icon: "fa fa-github fa-2x"
      weight: 2
      url: "https://github.com/smartepsh/"
    - name: Email
      icon: "fa fa-envelope fa-2x"
      weight: 3
      url: "mailto:fuzzes.oars-0s@icloud.com"

languages:
  en:
    contentDir: content/en
    languageName: English
    weight: 3
    title: "Head Canon Basement"
    params:
      author: "Kenton Wang"
      info: "Elixir Backend Development Engineer"
      description: "Personal blog website"
    menu:
      main:
        - name: About me
          url: "/en/index.html"
          weight: 1
        - name: Develop
          weight: 2
          url : "/en/develops.html"
        - name: Game
          weight: 3
          url: "/en/games.html"

  zh-cn:
    contentDir: content/zh-cn
    languageName: 简体中文
    weight: 1
    title: 脑补技能训练基地
    params:
      author: 岑儿姐
      info: "Elixir 后端开发工程师"
      description: 个人博客
    menu:
      main:
        - name: 关于
          url: "/"
          weight: 1
        - name: 开发
          weight: 2
          url : "/develops.html"
        - name: 游戏
          weight: 3
          url: "/games.html"
