baseURL = 'https://kenton.wang/'
languageCode = 'zh'
title = '脑补技能训练基地'
theme = 'coder'
defaultContentLanguage = "zh"

[params]
  author = "Kenton Wang"
  info = "Elixir Backend Development Engineer"
  avatarURL = "images/avatar.jpg"
  description = "Personal blog website"
  since = "2022"
  keywords = "blog,developer,personal,elixir"
  customJS = ["js/busuanzi.pure.mini.js"]

[[params.social]]
  name = "Email"
  icon = "fa fa-brands fa-qq fa-2x"
  weight = 1
  url = "https://jq.qq.com/?_wv=1027&k=gzB4umnU"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 2
  url = "https://github.com/smartepsh/"

[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  weight = 3
  url = "mailto:fuzzes.oars-0s@icloud.com"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Manuals"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"